all: ex1 ex2 ex3 ex4 ex5 ex6 ex7 ex8 ex9
ex1: ex1.c
	cc -o ex1 ex1.c
ex1.c: ex1.lex
	flex -o ex1.c ex1.lex
ex2: ex2.c
	cc -o ex2 ex2.c
ex2.c: ex2.lex
	flex -o ex2.c ex2.lex
ex3: ex3.c
	cc -o ex3 ex3.c
ex3.c: ex3.lex
	flex -o ex3.c ex3.lex
ex4: ex4.c
	cc -o ex4 ex4.c
ex4.c: ex4.lex
	flex -o ex4.c ex4.lex
ex5: ex5.c
	cc -o ex5 ex5.c
ex5.c: ex5.lex
	flex -o ex5.c ex5.lex
ex6: ex6.c
	cc -o ex6 ex6.c
ex6.c: ex6.lex
	flex -o ex6.c ex6.lex
ex7: ex7.c
	cc -o ex7 ex7.c
ex7.c: ex7.lex
	flex -o ex7.c ex7.lex
ex8: ex8.c
	cc -o ex8 ex8.c
ex8.c: ex8.lex
	flex -o ex8.c ex8.lex
ex9: ex9.c
	cc -o ex9 ex9.c
ex9.c: ex9.lex
	flex -o ex9.c ex9.lex

clean:
	rm *.c
	rm ex1 ex2 ex3 ex4 ex5 ex6 ex7 ex8 ex9
